import type {
  Activity,
  EventRequest,
  NetavilleEvent,
  Playlist,
  Screen,
  User,
} from './types';

/** Dates are seeded relative to today, so the panel never looks stale. */
function dayFromNow(offset: number): string {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
}

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 3600_000).toISOString();
}

export const seedUsers: User[] = [
  {
    id: 'u-admin',
    name: 'Stefan Perovski',
    email: 'stefan.perovski20@gmail.com',
    role: 'admin',
    online: true,
    lastSeen: hoursAgo(0),
    joinedAt: '2024-02-11',
    eventsAttended: 0,
    rsvps: 0,
    active: true,
  },
  {
    id: 'u-1',
    name: 'Quiet Otter',
    email: 'quiet.otter@students.finki.mk',
    role: 'student',
    online: true,
    lastSeen: hoursAgo(0.05),
    joinedAt: '2024-03-02',
    eventsAttended: 24,
    rsvps: 31,
    active: true,
  },
  {
    id: 'u-2',
    name: 'Marble Fox',
    email: 'marble.fox@students.finki.mk',
    role: 'student',
    online: true,
    lastSeen: hoursAgo(0.2),
    joinedAt: '2024-03-14',
    eventsAttended: 19,
    rsvps: 26,
    active: true,
  },
  {
    id: 'u-3',
    name: 'Slow Comet',
    email: 'slow.comet@students.finki.mk',
    role: 'student',
    online: false,
    lastSeen: hoursAgo(30),
    joinedAt: '2024-04-01',
    eventsAttended: 15,
    rsvps: 20,
    active: true,
  },
  {
    id: 'u-4',
    name: 'Paper Lantern',
    email: 'paper.lantern@students.finki.mk',
    role: 'student',
    online: true,
    lastSeen: hoursAgo(0.4),
    joinedAt: '2024-05-19',
    eventsAttended: 12,
    rsvps: 18,
    active: true,
  },
  {
    id: 'u-5',
    name: 'Copper Wren',
    email: 'copper.wren@students.finki.mk',
    role: 'student',
    online: false,
    lastSeen: hoursAgo(8),
    joinedAt: '2024-06-08',
    eventsAttended: 9,
    rsvps: 14,
    active: true,
  },
  {
    id: 'u-6',
    name: 'Amber Vale',
    email: 'amber.vale@students.finki.mk',
    role: 'student',
    online: false,
    lastSeen: hoursAgo(52),
    joinedAt: '2024-09-21',
    eventsAttended: 6,
    rsvps: 9,
    active: true,
  },
  {
    id: 'u-7',
    name: 'Northern Kite',
    email: 'northern.kite@students.finki.mk',
    role: 'student',
    online: false,
    lastSeen: hoursAgo(96),
    joinedAt: '2025-01-15',
    eventsAttended: 3,
    rsvps: 5,
    active: false,
  },
];

export const seedRequests: EventRequest[] = [
  {
    id: 'r-1',
    title: 'Figma for developers',
    requesterId: 'u-1',
    date: dayFromNow(9),
    startTime: '18:00',
    endTime: '20:00',
    room: 'Classroom',
    catering: 'Coffee & snacks',
    expectedParticipants: 30,
    status: 'pending',
    submittedAt: hoursAgo(5),
  },
  {
    id: 'r-2',
    title: 'Board games evening',
    requesterId: 'u-4',
    date: dayFromNow(12),
    startTime: '19:30',
    endTime: '23:00',
    room: 'Cafeteria',
    catering: 'None',
    expectedParticipants: 45,
    status: 'pending',
    submittedAt: hoursAgo(20),
  },
  {
    id: 'r-3',
    title: 'Rust reading group',
    requesterId: 'u-2',
    date: dayFromNow(4),
    startTime: '17:00',
    endTime: '18:30',
    room: 'Co-working floor',
    catering: 'None',
    expectedParticipants: 14,
    status: 'pending',
    submittedAt: hoursAgo(41),
  },
  {
    id: 'r-4',
    title: 'CV clinic with alumni',
    requesterId: 'u-5',
    date: dayFromNow(-3),
    startTime: '16:00',
    endTime: '19:00',
    room: 'Amphitheatre',
    catering: 'Full catering',
    expectedParticipants: 80,
    status: 'approved',
    submittedAt: hoursAgo(180),
  },
  {
    id: 'r-5',
    title: 'Crypto trading meetup',
    requesterId: 'u-6',
    date: dayFromNow(6),
    startTime: '20:00',
    endTime: '22:00',
    room: 'Amphitheatre',
    catering: 'Full catering',
    expectedParticipants: 120,
    status: 'rejected',
    reason: 'Commercial promotion is not allowed in campus spaces.',
    submittedAt: hoursAgo(150),
  },
];

export const seedEvents: NetavilleEvent[] = [
  {
    id: 'e-1',
    title: 'Cursor community build event',
    description:
      'Bring a laptop and an idea. We pair up, build something small in a single sitting, and demo it at the end.',
    date: dayFromNow(0),
    startTime: '18:00',
    endTime: '21:00',
    room: 'Amphitheatre',
    category: 'Workshop',
    priceInfo: 'Free',
    cafeteriaDiscount: 20,
    catering: 'Coffee & snacks',
    published: true,
  },
  {
    id: 'e-2',
    title: 'Iskustva.mk Quiz Night',
    description:
      'Teams of up to five, six rounds, one very opinionated host. No preparation needed.',
    date: dayFromNow(7),
    startTime: '19:00',
    endTime: '21:00',
    room: 'Amphitheatre',
    category: 'Quiz',
    priceInfo: '100 ден per team',
    cafeteriaDiscount: 10,
    catering: 'Coffee & snacks',
    published: true,
  },
  {
    id: 'e-3',
    title: 'Game night at Енергет',
    description: 'Consoles, board games and a very long table.',
    date: dayFromNow(8),
    startTime: '20:00',
    endTime: '22:00',
    room: 'Classroom',
    category: 'Social',
    priceInfo: 'Free',
    cafeteriaDiscount: 0,
    catering: 'None',
    published: true,
  },
  {
    id: 'e-4',
    title: 'TypeScript patterns in practice',
    description: 'A talk on the type-level tricks that actually pay off.',
    date: dayFromNow(11),
    startTime: '17:30',
    endTime: '19:00',
    room: 'Co-working floor',
    category: 'Talk',
    priceInfo: 'Free',
    cafeteriaDiscount: 15,
    catering: 'None',
    published: true,
  },
  {
    id: 'e-5',
    title: 'CV clinic with alumni',
    description: 'Bring a draft, leave with a better one.',
    date: dayFromNow(-3),
    startTime: '16:00',
    endTime: '19:00',
    room: 'Amphitheatre',
    category: 'Community',
    priceInfo: 'Free',
    cafeteriaDiscount: 25,
    catering: 'Full catering',
    published: false,
    fromRequestId: 'r-4',
  },
];

export const seedScreens: Screen[] = [
  {
    id: 's-1',
    name: 'Cafeteria wall',
    location: 'Ground floor, above the counter',
    pairingCode: '418823',
    paired: true,
    online: true,
    lastSeen: hoursAgo(0.01),
    activePlaylistId: 'p-1',
  },
  {
    id: 's-2',
    name: 'Amphitheatre foyer',
    location: 'Second floor entrance',
    pairingCode: '905147',
    paired: true,
    online: false,
    lastSeen: hoursAgo(19),
    activePlaylistId: 'p-2',
  },
  {
    id: 's-3',
    name: 'Co-working floor',
    location: 'Next to the lifts',
    pairingCode: '260934',
    paired: false,
    online: false,
    lastSeen: hoursAgo(72),
    activePlaylistId: null,
  },
];

export const seedPlaylists: Playlist[] = [
  {
    id: 'p-1',
    screenId: 's-1',
    name: 'Cafeteria rotation',
    active: true,
    updatedAt: hoursAgo(3),
    slides: [
      {
        id: 'sl-1',
        type: 'announcement',
        eventId: 'e-1',
        durationSec: 12,
        enabled: true,
      },
      {
        id: 'sl-2',
        type: 'marketing',
        headline: 'Double stamps today',
        cta: 'Every order earns 2× stamps',
        durationSec: 8,
        enabled: true,
      },
      {
        id: 'sl-3',
        type: 'announcement',
        eventId: 'e-2',
        durationSec: 12,
        enabled: true,
      },
      {
        id: 'sl-4',
        type: 'marketing',
        headline: 'Student prices all week',
        cta: 'Show your card at the counter',
        durationSec: 8,
        enabled: false,
      },
    ],
  },
  {
    id: 'p-2',
    screenId: 's-2',
    name: 'Foyer rotation',
    active: true,
    updatedAt: hoursAgo(26),
    slides: [
      {
        id: 'sl-5',
        type: 'announcement',
        eventId: 'e-3',
        durationSec: 15,
        enabled: true,
      },
      {
        id: 'sl-6',
        type: 'announcement',
        eventId: 'e-4',
        durationSec: 15,
        enabled: true,
      },
    ],
  },
];

export const seedActivity: Activity[] = [
  {
    id: 'a-1',
    kind: 'request',
    message: 'Quiet Otter submitted “Figma for developers”',
    at: hoursAgo(5),
  },
  {
    id: 'a-2',
    kind: 'screen',
    message: 'Cafeteria wall picked up a new playlist',
    at: hoursAgo(3),
  },
  {
    id: 'a-3',
    kind: 'request',
    message: 'Paper Lantern submitted “Board games evening”',
    at: hoursAgo(20),
  },
  {
    id: 'a-4',
    kind: 'rejection',
    message: 'Rejected “Crypto trading meetup”',
    at: hoursAgo(26),
  },
  {
    id: 'a-5',
    kind: 'approval',
    message: 'Approved “CV clinic with alumni”',
    at: hoursAgo(48),
  },
];
