/**
 * Lifts the traced SVG geometry out of netaville-intro.html into a TS module,
 * so the app ships the exact same path data as the original boot animation.
 *
 * Run with: node scripts/extract-logo.mjs
 */
import {readFileSync, writeFileSync} from 'node:fs';

const html = readFileSync(new URL('../../netaville-intro.html', import.meta.url), 'utf8');

/** Every `d="…"` inside the group whose class is `name`. */
function group(name) {
  const open = html.indexOf(`<g class="${name}">`);
  if (open === -1) {
    throw new Error(`group ${name} not found`);
  }
  const close = html.indexOf('</g>', open);
  const body = html.slice(open, close);
  return [...body.matchAll(/ d="([^"]+)"/g)].map(match => match[1]);
}

const slab = /<path class="slab" d="([^"]+)"/.exec(html)[1];
const tiles = [...html.matchAll(/<rect class="dot" x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)"/g)].map(
  ([, x, y, width, height]) => ({
    x: Number(x),
    y: Number(y),
    width: Number(width),
    height: Number(height),
  }),
);

/** Centre of a path's bounding box, in mark-space (before the 92/81 offset). */
function centre(d) {
  const points = d
    .replace(/[A-Za-z]/g, ' ')
    .trim()
    .split(/\s+/)
    .map(pair => pair.split(',').map(Number))
    .filter(pair => pair.length === 2 && pair.every(Number.isFinite));
  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  return {
    x: (Math.min(...xs) + Math.max(...xs)) / 2,
    y: (Math.min(...ys) + Math.max(...ys)) / 2,
  };
}

const out = `// AUTO-GENERATED by scripts/extract-logo.mjs from netaville-intro.html.
// Path data is copied verbatim — do not reformat or "optimise" it.

export const MARK_OFFSET = {x: 92, y: 81};
export const VIEW_BOX = 400;

export const slabPath = ${JSON.stringify(slab)};

export const cyanPaths = ${JSON.stringify(group('p-cyan'), null, 2)};

export const greyPaths = ${JSON.stringify(group('p-grey'), null, 2)};

export const rayPaths = ${JSON.stringify(group('p-yellow'), null, 2)};

/** Bounding-box centres, so each ray scales about itself like the CSS did. */
export const rayCentres = ${JSON.stringify(group('p-yellow').map(centre), null, 2)};

export const tracePaths = ${JSON.stringify(group('p-coral'), null, 2)};

export const corePaths = ${JSON.stringify(group('p-core'), null, 2)};

export const glyphPaths = ${JSON.stringify(group('word'), null, 2)};

export const tiles = ${JSON.stringify(tiles, null, 2)};

export const CORE = {cx: 83, cy: 109, r: 25};

export const palette = {
  ink: '#2500CA',
  cyan: '#01BEFE',
  gold: '#FFC700',
  coral: '#FF593F',
  grey: '#E6E6E6',
  tile: '#fff',
} as const;
`;

writeFileSync(new URL('../src/data/logo.ts', import.meta.url), out);
console.log(
  `slab:1 cyan:${group('p-cyan').length} grey:${group('p-grey').length} rays:${group('p-yellow').length} traces:${group('p-coral').length} core:${group('p-core').length} glyphs:${group('word').length} tiles:${tiles.length}`,
);
