/**
 * Pulls icon geometry out of the SVGs that live next to the app.
 *
 * Run with: node scripts/extract-icons.mjs
 */
import {readFileSync, writeFileSync} from 'node:fs';

const sources = {
  events: 'events.svg',
  menu: 'menu:coffee.svg',
  card: 'card.svg',
  ranks: 'ranks.svg',
  calendar: 'calendar.svg',
  coffeeBeans: 'coffee-beans.svg',
  specialty: 'specialty.svg',
  notCoffee: 'not coffee.svg',
};

const entries = Object.entries(sources).map(([name, file]) => {
  const svg = readFileSync(new URL(`../../${file}`, import.meta.url), 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(match => match[1]);
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? '0 0 24 24';
  if (paths.length === 0) {
    throw new Error(`no path in ${file}`);
  }
  return `  ${name}: {viewBox: ${JSON.stringify(viewBox)}, paths: ${JSON.stringify(paths)}},`;
});

writeFileSync(
  new URL('../src/data/appIcons.ts', import.meta.url),
  `// AUTO-GENERATED by scripts/extract-icons.mjs from the project's SVG files.

export const appIcons = {
${entries.join('\n')}
} as const;

export type AppIconName = keyof typeof appIcons;
`,
);
console.log(Object.keys(sources).join(' '));
