/**
 * Renders a fixed set of DiceBear "croodles-neutral" avatars to a TS module so
 * the app ships them as inline SVG — no network calls at runtime.
 *
 * Run with: node scripts/generate-avatars.mjs
 */
import {writeFileSync} from 'node:fs';
import {createAvatar} from '@dicebear/core';
import {croodlesNeutral} from '@dicebear/collection';

const seeds = [
  'stefan',
  'ana',
  'marko',
  'elena',
  'bojan',
  'iva',
  'darko',
  'teodora',
  'nikola',
  'sara',
  'filip',
  'maja',
];

const entries = seeds.map(seed => {
  const svg = createAvatar(croodlesNeutral, {
    seed,
    size: 96,
    radius: 50,
    backgroundColor: ['E7E4FB', 'FBE1DB', 'D8F2FB', 'FDEFC4'],
  }).toString();

  return `  ${seed}: ${JSON.stringify(svg)},`;
});

const file = `// AUTO-GENERATED by scripts/generate-avatars.mjs — do not edit by hand.
// DiceBear "Croodles Neutral" by vijay verma, licensed CC BY 4.0.
// https://www.dicebear.com/styles/croodles-neutral/

export const avatarSvgs = {
${entries.join('\n')}
} as const;

export type AvatarSeed = keyof typeof avatarSvgs;

export const avatarSeeds = Object.keys(avatarSvgs) as AvatarSeed[];

/** Picks a stable avatar for any string (event id, name, …). */
export function avatarFor(key: string): string {
  let hash = 0;
  for (let index = 0; index < key.length; index += 1) {
    hash = (hash * 31 + key.charCodeAt(index)) >>> 0;
  }
  const seed = avatarSeeds[hash % avatarSeeds.length] ?? avatarSeeds[0]!;
  return avatarSvgs[seed];
}
`;

writeFileSync(new URL('../src/data/avatars.ts', import.meta.url), file);
console.log(`Wrote ${seeds.length} avatars to src/data/avatars.ts`);
